### PR TITLE
Add info regarding fonts needed for stringrenderer_test

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by stweil** [comment]
Could you please add some information (origin, license of the fonts) to testing/README.md?

**Comment by Shreeshrii** [comment]
@stweil I have added the info regarding origin, license of the fonts to README.md.

@zdenop Please review whether the licensing is compatible. Thanks!

**Comment by Shreeshrii** [comment]
@zdenop  I have deleted the font files. Info regarding the source of fonts has been added to README.

**Comment by stweil** [comment]
@zdenop, even if the fonts are now deleted in the latest revision, they are still part of the Git history. This increases the size and might be a license problem. Maybe the critical commits should be removed completely by rebasing the test repository (something which normally must not be done).

**Comment by zdenop** [comment]
@stweil : if you know how to do it, please do it.

**Comment by stweil** [comment]
Missing rights ...

**Comment by zdenop** [comment]
try now...

**Comment by stweil** [comment]
Thank you. @Shreeshrii, I rebased and squashed your last commits for test now, so the critical fonts are no longer part of the Git commit history.

**Pull request merged**
